---
title: "Getting Started with dismapr"
editor_options: 
  chunk_output_type: console
---
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE)

# devtools::load_all() 
# devtools::install_local(force = T)
```

Example script demonstrating how to use the dismapr package for retrieving
interpolated distance-weighted biomass data from NOAA's DisMAP.

```{r setup}
library(dismapr) 
library(dplyr)
library(DT)
library(glue)
library(here)
library(sf)
library(terra)
```

## 1. Indicators

Example 1: Get indicators data for American Lobster in Northeast US Spring

```{r}
tbl_lobster_indicators <- dm_get_indicators(
  common_name = "American lobster", 
  region      = "Northeast US",
  season      = "Spring")
tbl_lobster_indicators

# plot center of gravity changes over time
dm_plot_indicators(
  tbl_lobster_indicators,
  title = "American Lobster Center of Gravity")
```

## 2. Rasters

Example 2: Download interpolated biomass rasters for Summer Flounder in NEUS Spring

```{r}
# show table of dataset_codes for available regions and seasons
dm_datasets |> 
  sf::st_drop_geometry() |>
  DT::datatable()

# show map of dataset_codes
dm_plot_datasets(dm_datasets)
```

```{r}
# pick the Northeast US Spring dataset
dataset_code <- "NEUS_SPR"

# show list of available region_seasons (where season may be optional)
dm_get_dataset_layers(dataset_code)

# pick the layer (i.e., species): summer flounder (Paralichthys dentatus)
layer     <- "Paralichthys dentatus"
sp_common <- "SummerFlounder"

# show list of available years
dm_get_dataset_layer_years(dataset_code, layer)

# pick a set of years
years <- 2015:2019

# create directory for downloads
output_dir <- here::here("inst/test")
dir.create(output_dir, showWarnings = F, recursive = T)

# download each raster
for (yr in years) { # yr = years[1]
  tif <- glue::glue("{output_dir}/{dataset_code}_IDW_{sp_common}_{yr}.tif")

  r <- dm_get_raster(
    dataset_code,
    layer,
    yr,
    tif)
}

yr <- 2015
r <- terra::rast(glue::glue("{output_dir}/{dataset_code}_IDW_{sp_common}_{yr}.tif"))
r
```

### Plot raster

```{r}
# interactive plot
dm_plot_raster(
  r, 
  interactive = TRUE,
  main = glue::glue("{dataset_code} {sp_common}, {yr}"))

# static plot
dm_plot_raster(
  r,
  interactive = FALSE,
  title = glue::glue("{dataset_code} {sp_common}, {yr}"))
```

## 3. Surveys

```{r}
dataset_code <- "NEUS_SPR"
year <- 2015

pts_yr <- dm_get_survey_locations(dataset_code, where = glue::glue("Year = {year}"))
# show a sample of first 100 rows
head(pts_yr, 100) |> 
  DT::datatable()

# summarize by biomass
pts_yr_sum <- pts_yr |>
  dplyr::group_by(Longitude, Latitude) |>
  dplyr::summarize(
    wtcpue = sum(WTCPUE), .groups = "drop")

# interactive plot
dm_plot_survey_locations(
  pts_yr_sum, 
  interactive = TRUE,
  title = glue::glue("Northeast US Spring Survey Locations, {year}"))

# static plot
dm_plot_survey_locations(
  pts_yr_sum, 
  interactive = FALSE,
  title = glue::glue("Northeast US Spring Survey Locations, {year}"))
```
